name: apollo-application
servers:
  - name: http1
    address: 0.0.0.0
    port: 8080
request-mappings:
  - name: root
    path: /*
    handler: x.Mux
    methods:
      - get
      - head
      - post
      - put
      - patch
      - delete
      - options
      - trace
  - name: hello
    path: /hello
    handler: x.HelloMux
    methods: [get,post]