name: apollo-application
servers:
  address: 0.0.0.0
  port: 8080
routers:
  - name: root
    path: /*
    handler: x.Mux
    methods:
      - get
      - head
      - post
      - put
      - patch
      - delete
      - options
      - trace
  - name: hello
    path: /hello/{userid}
    handler: x.HelloMux
    methods: [get,post]